setw -g mode-keys vi

bind-key x kill-pane

set-option -g allow-passthrough on

set -g @resurrect-strategy-nvim 'session'

set -g @plugin 'tmux-plugins/tmux-yank'

set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'sainnhe/tmux-fzf'

set -g @plugin 'tmux-plugins/tmux-pain-control'

set -g @plugin 'rickstaa/tmux-notify'

set -g @plugin 'jaclu/tmux-mouse-swipe'

set -g @plugin 'nhdaly/tmux-better-mouse-mode'

set -g @plugin 'kenos1/tmux-cht-sh'

set -g @plugin 'laktak/extrakto'

set -g @plugin 'schasse/tmux-jump'

set -g @plugin 'MunifTanjim/tmux-suspend'

set-option -g mouse on

bind r source-file "$HOME/.tmux.conf"

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

set -g @plugin 'MunifTanjim/tmux-mode-indicator'

mode_separator="#[default]#{?client_prefix,#[fg="#7daea3"],
#{?pane_in_mode,#[fg="#e78a4e"],#{?pane_synchronized,#[fg="#e78a4e"],#[fg="#89b482"]}}}"

set -g @mode_indicator_prefix_prompt " WAIT $mode_separator"
set -g @mode_indicator_prefix_mode_style bg="#7daea3",fg="#282828"
set -g @mode_indicator_copy_prompt " COPY $mode_separator"
set -g @mode_indicator_copy_mode_style bg="#e78a4e",fg="#282828"
set -g @mode_indicator_sync_prompt " SYNC $mode_separator"
set -g @mode_indicator_sync_mode_style bg=#ea6962,fg="#282828"
set -g @mode_indicator_empty_prompt " TMUX $mode_separator"
set -g @mode_indicator_empty_mode_style bg="#89b482",fg="#282828"

set -g @plugin 'MunifTanjim/tmux-suspend'

set -g @suspend_suspended_options " \
  @mode_indicator_custom_prompt:: SUSPEND $mode_separator, \
  @mode_indicator_custom_mode_style::bg=#89b482\\,fg=#282828, \
"

set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g @resurrect-processes 'vi -> nvim'
set -g @resurrect-processes 'vim -> nvim'

if-shell "test -f $HOME/.tmuxline.conf" "source $HOME/.tmuxline.conf"

run '~/.tmux/plugins/tpm/tpm'
