setw -g mode-keys vi

bind-key x kill-pane

set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g @resurrect-strategy-vim 'session'

set -g @resurrect-strategy-nvim 'session'

set -g @plugin 'tmux-plugins/tmux-yank'

set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'sainnhe/tmux-fzf'

set -g @plugin 'tmux-plugins/tmux-pain-control'

set -g @plugin 'rickstaa/tmux-notify'

set -g @plugin 'jaclu/tmux-mouse-swipe'

set -g @plugin 'nhdaly/tmux-better-mouse-mode'

set -g @plugin 'kenos1/tmux-cht-sh'

set -g @plugin 'laktak/extrakto'

set -g @plugin 'schasse/tmux-jump'

set -g @plugin 'MunifTanjim/tmux-suspend'

set-option -g mouse on

bind r source-file "$HOME/.tmux.conf"

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

run '~/.tmux/plugins/tpm/tpm'
