font_family      JetBrainsMono Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 12.5

background_opacity 0.92

foreground            #ebdbb2
background            #272727
selection_foreground  #655b53
selection_background  #ebdbb2
url_color             #d65c0d

background #282828
foreground #d4be98

selection_background #d4be98
selection_foreground #282828

cursor #a89984
cursor_text_color background

active_tab_foreground   #fbf1c7
active_tab_background   #665c54
inactive_tab_foreground #a89984
inactive_tab_background #3c3836
tab_bar_edge            bottom
tab_bar_style           powerline
active_tab_font_style   bold

# Black
color0 #665c54
color8 #928374

# Red
color1 #ea6962
color9 #ea6962

# Green
color2 #a9b665
color10 #a9b665

# Yellow
color3 #e78a4e
color11 #d8a657

# Blue
color4 #7daea3
color12 #7daea3

# Magenta
color5 #d3869b
color13 #d3869b

# Cyan
color6 #89b482
color14 #89b482

# White
color7 #d4be98
color15 #d4be98

map ctrl+shift+enter new_tab_with_cwd

enabled_layouts splits

# Create a new window splitting the space used by the existing one so that
# the two windows are placed one above the other
map ctrl+5 launch --location=hsplit

# Create a new window splitting the space used by the existing one so that
# the two windows are placed side by side
map ctrl+6 launch --location=vsplit

# Create a new window splitting the space used by the existing one so that
# the two windows are placed side by side if the existing window is wide or
# one above the other if the existing window is tall.
map ctrl+4 launch --location=split

# Rotate the current split, changing its split axis from vertical to
# horizontal or vice versa
map ctrl+7 layout_action rotate

# Move the active window in the indicated direction
map shift+up move_window up
map shift+left move_window left
map shift+right move_window right
map shift+down move_window down

# Move the active window to the indicated screen edge
map ctrl+shift+up layout_action move_to_screen_edge top
map ctrl+shift+left layout_action move_to_screen_edge left
map ctrl+shift+right layout_action move_to_screen_edge right
map ctrl+shift+down layout_action move_to_screen_edge bottom

# Switch focus to the neighboring window in the indicated direction
map ctrl+left neighboring_window left
map ctrl+right neighboring_window right
map ctrl+up neighboring_window up
map ctrl+down neighboring_window down

map ctrl+l resize_window narrower
map ctrl+h resize_window wider
map ctrl+k resize_window taller
map ctrl+j resize_window shorter 3
# reset all windows in the tab to default sizes
map ctrl+home resize_window reset
