shell_integration enabled

font_family      JetBrainsMono NF
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 12.5

background_opacity 0.95

tab_bar_edge            bottom
tab_bar_style           powerline
active_tab_font_style   bold

background #24283b
foreground #c0caf5
selection_background #2e3c64
selection_foreground #c0caf5
url_color #73daca
cursor #c0caf5
cursor_text_color #24283b

# Tabs
active_tab_background #7aa2f7
active_tab_foreground #1f2335
inactive_tab_background #292e42
inactive_tab_foreground #565f89
#tab_bar_background #1d202f

# Windows
active_border_color #7aa2f7
inactive_border_color #292e42

# normal
color0 #1d202f
color1 #f7768e
color2 #9ece6a
color3 #e0af68
color4 #7aa2f7
color5 #bb9af7
color6 #7dcfff
color7 #a9b1d6

# bright
color8 #414868
color9 #f7768e
color10 #9ece6a
color11 #e0af68
color12 #7aa2f7
color13 #bb9af7
color14 #7dcfff
color15 #c0caf5

# extended colors
color16 #ff9e64
color17 #db4b4b

enabled_layouts splits,stack

window_resize_step_cells 2
window_resize_step_lines 2

window_border_width 0.5pt

map ctrl+s>" launch --location=hsplit --cwd=last_reported
map ctrl+s>% launch --location=vsplit --cwd=last_reported

map ctrl+s>c launch --location=split

map ctrl+s>space layout_action rotate

map kitty_mod+enter new_tab_with_cwd

map kitty_mod+f5 load_config_file /home/maxim/.config/kitty/kitty.conf

map ctrl+s>, set_tab_title

map ctrl+s>left neighboring_window left
map ctrl+s>right neighboring_window right
map ctrl+s>up neighboring_window up
map ctrl+s>down neighboring_window down

map ctrl+s>h neighboring_window left
map ctrl+s>l neighboring_window right
map ctrl+s>k neighboring_window up
map ctrl+s>j neighboring_window down

map kitty_mod+up move_window up
map kitty_mod+left move_window left
map kitty_mod+right move_window right
map kitty_mod+down move_window down

map alt+h resize_window narrower
map alt+l resize_window wider
map alt+k resize_window taller
map alt+j resize_window shorter 3

map ctrl+s>z toggle_layout stack

map kitty_mod+1 goto_tab 1
map kitty_mod+2 goto_tab 2
map kitty_mod+3 goto_tab 3
map kitty_mod+4 goto_tab 4
map kitty_mod+5 goto_tab 5
map kitty_mod+6 goto_tab 6
map kitty_mod+7 goto_tab 7
map kitty_mod+8 goto_tab 8
map kitty_mod+9 goto_tab 9
map kitty_mod+0 goto_tab 10
