version: 2
tools:
  gitcommit-gitlint: &gitcommit-gitlint
    lint-command: gitlint --config /home/maxim/.gitlint
    lint-stdin: true
    lint-formats: ['%l: %m: "%r"', '%l: %m', '%f:%l:%c: %m']
  markdown-pandoc: &markdown-pandoc
    format-command: pandoc -f markdown -t gfm -sp --tab-stop=2 --columns=79
    format-stdin: true
  rst-pandoc: &rst-pandoc
    format-command: pandoc -f rst -t rst -s --columns=79
    format-stdin: true
languages:
  gitcommit:
    - <<: *gitcommit-gitlint
  markdown:
    - <<: *markdown-pandoc
  rst:
    - <<: *rst-pandoc
