vim.keymap.set("n", "<leader>1", "<Cmd>tabn 1<CR>")
vim.keymap.set("n", "<leader>2", "<Cmd>tabn 2<CR>")
vim.keymap.set("n", "<leader>3", "<Cmd>tabn 3<CR>")
vim.keymap.set("n", "<leader>4", "<Cmd>tabn 4<CR>")
vim.keymap.set("n", "<leader>5", "<Cmd>tabn 5<CR>")
vim.keymap.set("n", "<leader>6", "<Cmd>tabn 6<CR>")
vim.keymap.set("n", "<leader>7", "<Cmd>tabn 7<CR>")
vim.keymap.set("n", "<leader>8", "<Cmd>tabn 8<CR>")
vim.keymap.set("n", "<leader>9", "<Cmd>tabn 9<CR>")
vim.keymap.set("n", "<leader>$", "<Cmd>tablast<CR>")

vim.keymap.set("n", "[b", ":tabnext<CR>")
vim.keymap.set("n", "b]", ":tabprevious<CR>")

vim.keymap.set("n", "td1", "<Cmd>tabc 1<CR>")
vim.keymap.set("n", "td2", "<Cmd>tabc 2<CR>")
vim.keymap.set("n", "td3", "<Cmd>tabc 3<CR>")
vim.keymap.set("n", "td4", "<Cmd>tabc 4<CR>")
vim.keymap.set("n", "td5", "<Cmd>tabc 5<CR>")
vim.keymap.set("n", "td6", "<Cmd>tabc 6<CR>")
vim.keymap.set("n", "td7", "<Cmd>tabc 7<CR>")
vim.keymap.set("n", "td8", "<Cmd>tabc 8<CR>")
vim.keymap.set("n", "td9", "<Cmd>tabc 9<CR>")
vim.keymap.set("n", "td$", "<Cmd>tabc $<CR>")

vim.keymap.set("n", "td", ":tabc<CR>")
vim.keymap.set("n", "to", ":tabo<CR>")
